[package]
name = "uftserver"
version = "0.1.0"
authors = ["red75prime <red75prim@gmail.com>"]

[dependencies]
bytes = "0.4"
byteorder = "1.2"
failure = "0.1"
futures = "0.1.17"
futures-cpupool = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
tokio = "0.1"
rand = "0.4"
